name: WanQing's Blog
description: 这是一个使用Jekyll搭建的个人日志站。
meta_description: "New Jekyll site."

markdown: rdiscount
highlighter: pygments
logo: false
paginate: 10
baseurl: /
domain_name: 'http://wanqingwong.com'

# Details for the RSS feed generator
url:            'http://wanqingwong.com'
author:         'wwq'

analytics:
  provider: google
  google :
    tracking_id: UA-47052968-1
